const products = [
    {
      name: "Basic Cake Topper",
      category: "toppers",
      price: 15,
      imageSrc: "CakeTopper.jpg",
      min: 1,
      max: 10,
      options: {
        color: [
          "glitter gold",
          "glitter silver",
          "glitter blue",
          "glitter black",
          "glitter pink",
          "glitter fuschia",
          "glitter purple",
          "chrome gold",
          "chrome silver",
          "blue",
          "white",
          "black",
          "purple",
          "red",
          "custom",
          "pink",
        ],
      },
    },
    {
      name: "3D Cake Topper",
      category: "toppers",
      price: 25,
      imageSrc: "3DCakeTopper.jpg",
      min: 1,
      max: 10,
      options: {
        theme: ["mermaid", "construction", "dinosaur", "unicorn", "custom"],
      },
    },
    {
      name: "Shaker Cake Topper",
      category: "toppers",
      price: 30,
      imageSrc: "ShakerCakeTopper.jpg",
      min: 1,
      max: 10,
      options: {
        theme: ["mermaid", "construction", "dinosaur", "unicorn", "custom"],
        ledLight: false,
      },
    },
    {
      name: "basic Cupcake Topper",
      category: "toppers",
      price: 0.5,
      imageSrc: "CupcakeTopper.jpg",
      min: 12,
      max: 99,
      options: {
        color: [
          "glitter gold",
          "glitter silver",
          "glitter blue",
          "glitter black",
          "glitter pink",
          "glitter fuschia",
          "glitter purple",
          "chrome gold",
          "chrome silver",
          "blue",
          "white",
          "black",
          "purple",
          "red",
          "custom",
          "pink",
        ],
      },
    },
    {
      name: "Intricate Cupcake Topper",
      category: "toppers",
      price: 0.75,
      imageSrc: "IntricateCupcakeTopper.jpg",
      min: 12,
      max: 99,
      options: {
        color: [
          "glitter gold",
          "glitter silver",
          "glitter blue",
          "glitter black",
          "glitter pink",
          "glitter fuschia",
          "glitter purple",
          "chrome gold",
          "chrome silver",
          "blue",
          "white",
          "black",
          "purple",
          "red",
          "custom",
          "pink",
        ],
      },
    },
    {
      name: "Custom Chip Bags",
      category: "chips",
      price: 6.75,
      imageSrc: "CustomChipBags.jpg",
      min: 10,
      max: 150,
      options: {
        theme: ["mermaid", "construction", "dinosaur", "unicorn", "custom"],
      },
    },
    {
      name: "Custom Pringle chips",
      category: "chips",
      price: 7,
      imageSrc: "CustomPringleChips.jpg",
      min: 10,
      max: 150,
      options: {
        theme: ["mermaid", "construction", "dinosaur", "unicorn", "custom"],
      },
    },
    {
      name: "Piñatas",
      category: "pinatas",
      price: 20,
      imageSrc: "pinata.jpg",
      min: 1,
      max: 5,
      options: {
        size: ["6", "18", "2'", "custom"],
      },
    },
    {
      name: "Cake Topper Set",
      category: "toppers",
      price: 22,
      imageSrc: "cake-topper-set.jpg",
      min: 1,
      max: 1,
      options: {},
    },
    {
      name: "Acrylic Circle Cake Topper",
      category: "toppers",
      price: 28,
      imageSrc: "acrylic-circle-topper.jpg",
      min: 1,
      max: 5,
      options: {},
    },
    {
      name: "Number Candles",
      category: "party",
      price: 10,
      imageSrc: "number-candles.jpg",
      min: 1,
      max: 1,
      options: {
        number: ["custom"],
      },
    },
    {
      name: "Goodie Box",
      category: "boxes",
      price: 7,
      imageSrc: "goodie-box.jpg",
      min: 1,
      max: 30,
      options: {
        shape: ["custom"],
      },
    },
    {
      name: "Combo 1",
      category: "packages",
      price: 15,
      imageSrc: "combo1.jpg",
      min: 10,
      max: 20,
      options: {
        theme: ["mermaid", "construction", "dinosaur", "unicorn", "custom"],
        shirts: false,
        balloons: false,
      },
    },
    {
      name: "Combo 2",
      category: "packages",
      price: 23,
      imageSrc: "combo2.jpg",
      min: 10,
      max: 20,
      options: {
        theme: ["mermaid", "construction", "dinosaur", "unicorn", "custom"],
        shirts: false,
        balloons: false,
      },
    },
    {
      name: "Goodie Box (empty)",
      category: "boxes",
      price: 6,
      imageSrc: "goodie-box-empty.jpg",
      min: 5,
      max: 50,
      options: {
        shape: ["custom"],
      },
    },
    {
      name: "Goodie Bag (empty)",
      category: "boxes",
      price: 6,
      imageSrc: "goodie-bag-empty.jpg",
      min: 5,
      max: 50,
      options: {
        theme: ["mermaid", "construction", "dinosaur", "unicorn", "custom"],
        shirts: false,
        balloons: false,
      },
    },
    {
      name: "Montly Banner",
      category: "banners",
      price: 30,
      imageSrc: "montlyBanner.jpg",
      min: 1,
      max: 5,
      options: {
        theme: ["mermaid", "construction", "dinosaur", "unicorn", "custom"],
      },
    },
    {
      name: "Photo booth frame",
      category: "photography",
      price: 40,
      imageSrc: "photoBoothFrame.jpg",
      min: 1,
      max: 5,
      options: {
        theme: ["mermaid", "construction", "dinosaur", "unicorn", "custom"],
      },
    },
    {
      name: "Cardstock high chair banner",
      category: "banners",
      price: 18,
      imageSrc: "highChairBanner.jpg",
      min: 1,
      max: 5,
      options: {
        theme: ["mermaid", "construction", "dinosaur", "unicorn", "custom"],
      },
    },
    {
      name: "Fabric high chair banner",
      category: "banners",
      price: 28,
      imageSrc: "FabricHighChairBanner.jpg",
      min: 1,
      max: 5,
      options: {
        theme: ["mermaid", "construction", "dinosaur", "unicorn", "custom"],
      },
    },
    {
      name: "Custom Keychains",
      category: "epoxy",
      price: 10,
      imageSrc: "keychain.jpg",
      min: 10,
      max: 50,
      options: {
        theme: ["mermaid", "construction", "dinosaur", "unicorn", "custom"],
      },
    },
    {
      name: "Personalized notebook",
      category: "epoxy",
      price: 40,
      imageSrc: "notebook.jpg",
      min: 1,
      max: 10,
      options: {
        theme: ["mermaid", "construction", "dinosaur", "unicorn", "custom"],
      },
    },
    {
      name: "Party hats",
      category: "party",
      price: 10,
      imageSrc: "partyHats.jpg",
      min: 1,
      max: 50,
      options: {
        theme: ["mermaid", "construction", "dinosaur", "unicorn", "custom"],
      },
    },
    {
      name: "Ceramic frame",
      category: "home decorations",
      price: 50,
      imageSrc: "CeramicFrame.jpg",
      min: 1,
      max: 50,
      options: {
        theme: ["mermaid", "construction", "dinosaur", "unicorn", "custom"],
      },
    },
    {
      name: "Custom frames",
      category: "home decorations",
      price: 15,
      imageSrc: "frames.jpg",
      min: 1,
      max: 50,
      options: {
        theme: ["mermaid", "construction", "dinosaur", "unicorn", "custom"],
      },
    },
    {
      name: "3D letters/numbers",
      category: "party",
      price: 15,
      imageSrc: "letters.jpg",
      min: 3,
      max: 50,
      options: {
        theme: ["mermaid", "construction", "dinosaur", "unicorn", "custom"],
        qty: 0,
      },
    },
  ];

  export default products;
