FROM node:18-alpine AS pruner

RUN apk add --no-cache libc6-compat
RUN apk update

# Set working directory
WORKDIR /app
RUN yarn global add turbo
COPY . .
RUN turbo prune --scope=strapi --docker


# Add lockfile and package.json's of isolated subworkspace
FROM node:18-alpine AS builder

# curl for installing pnpm in the layer below, libc6-compat for turborepo's post
# installation script
RUN apk --no-cache add curl libc6-compat

# Add pnpm
RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

WORKDIR /app

# First install the dependencies (as they change less often)
COPY .gitignore .gitignore
COPY --from=pruner /app/out/json/ .
COPY --from=pruner /app/out/pnpm-lock.yaml .
RUN pnpm fetch
RUN pnpm install -r --offline

# Build the project
COPY --from=pruner /app/out/full/ .
COPY turbo.json turbo.json
RUN pnpm exec turbo run build --filter=strapi


FROM node:18-alpine AS runner

# curl for installing pnpm in the layer below, libc6-compat for turborepo's post
# installation script
RUN apk --no-cache add curl libc6-compat

# Add pnpm
RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

WORKDIR /app

COPY --from=builder /app/ .

CMD pnpm run start --filter strapi
